services:
  postgres:
    image: postgres:16
    container_name: novashop-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-novashop_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - novashop-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: novashop-backend
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB:-novashop_db}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    ports:
      - "8080:8080"
    networks:
      - novashop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: novashop-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    networks:
      - novashop-network

volumes:
  postgres_data:

networks:
  novashop-network:
